ArthurG/Kijiji-Repost-Headless

- .gitignore
- GenerateInfFile.py
- KijijiApi.py
- KijijiCmd.py
- README.md
Fixed functionality of ad reposting. Kijiji must have recently updated their site so that if you try to repost the same ad again too soon after deleting the old one, the site will post the ad but then automatically remove it if reposted too soon. A waiting period has been added after deleting the old ad before it attempts to repost the same ad afterwards.
Added multiline ad description support when generating ad inf files. Re-worded question prompts.
> Fixed ad reposting and added multiline ad description support.

- kijiji_repost_headless/kijiji_api.py
> Modify get_ad_details to conform to new Kijiji RESTFUL API

- kijiji_repost_headless/kijiji_api.py
- kijiji_repost_headless/kijiji_cmd.py
- Added proper function docstrings
- Cleaned up some whitespace
- Re-enabled printing help menu when no arguments are passed to kijiji_cmd.py
> Added function docstrings and re-enabled help when no args are passed

- kijiji_repost_headless/kijiji_api.py
> Fix error with '\n' instead of newline character

- kijiji_repost_headless/kijiji_api.py
- kijiji_repost_headless/kijiji_cmd.py
There is a new required token that is required when uploading photos. 
This update scrapes the token and uses it when uploading photos
Fixes #32
> Fix image upload

- kijiji_repost_headless/kijiji_cmd.py
- Reverses part of #34
- Might solve #37
> Change sleep time to 100s

- README.md
- kijiji_repost_headless/__main__.py
- kijiji_repost_headless/generate_inf_file.py
- kijiji_repost_headless/kijiji_api.py
This change makes a clearer distinction between the command line options and the API.
The kijiji_api can be used for multiple different projects, while __main__ is a wrapper for kijiji_api useful for posting from command line
Also includes some code cleanup
> Use __main__ over kijiji_cmd.py

- kijiji_repost_headless/__main__.py
> Fix building inf file command

- kijiji_repost_headless/__main__.py
> Add 3 minute warning for when ads are reposted

- kijiji_repost_headless/generate_post_file.py
- kijiji_repost_headless/get_ids.py
- **Added multi-address support - prompt for a choice if multiple addresses found in search**
- Added more error handling
- Dump yaml fields in a more sensible order (using OrderedDict)
- Option to omit username and password from ad file if left empty
- Renamed variables from camelCase to snake_case
- Some double quotes changed to single quotes
> Build ad file fixes

- kijiji_repost_headless/kijiji_api.py
Same change as previous pull request.
> Changed character limit of ad title from 10 to 8.

- kijiji_repost_headless/generate_post_file.py
> Use OpenStreetMap API instead of Google Maps API for geocoding

- kijiji_repost_headless/kijiji_api.py
> Fix login error

- kijiji_repost_headless/__main__.py
https://github.com/ArthurG/Kijiji-Repost-Headless/issues/143#issue-462277512
This adds messages during the 3 minute countdown at 1 minute, 2 minutes, and again with 30s and 10s remaining.
> Issue #143, Countdown timer

- run_tests
- test/get_ids_fake.py
- test/test_generate_inf.py
Run unit test via:
python3 -m unittest discover
> Fix testing

- kijiji_repost_headless/get_ids.py
The missing space was bugging me...
> Add 'missing' space in "Where are you?"

- kijiji_repost_headless/generate_post_file.py
- kijiji_repost_headless/kijiji_api.py
Updated the Kijiji API to use a random user agent. Chosen from either MacOSX/Windows Chrome/FF. I've created an ad in the buy and sell and I haven't had an issue.
❤️
> updated ua and random agent switcher

- kijiji_repost_headless/__main__.py
- kijiji_repost_headless/kijiji_api.py
> Fix XSRF token issue

- kijiji_repost_headless/kijiji_api.py
https://github.com/ArthurG/Kijiji-Repost-Headless/issues/185
> Remove hints property from login request to fix INTERNAL_SERVER_ERROR

- kijiji_repost_headless/kijiji_api.py
To fix the login failure discussed here: https://github.com/ArthurG/Kijiji-Repost-Headless/issues/217
Credit: @JohnBakery  https://github.com/JohnBakery
> update kijiji api with new kijiji address for fixing login failure

- kijiji_repost_headless/kijiji_api.py
Appends the proper xsrf token
Tested and working on mac and raspberry pi (raspbian)
> Fix deleting and nuking - Using zalmoxis fix

- kijiji_repost_headless/__main__.py
- kijiji_repost_headless/kijiji_api.py
This PR migrates the Kijiji API to the mingle.kijiji.ca api (thanks to rybodiddly/Kijiji-Reposter/ for the inspiration!)
To easily test this new feature, I also add a `repost_all` command to the CLI tool.
> Revive extension by supporting repost all working command 
